apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-ebs-pvc
  namespace: emcp-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: ebs-sc