apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongodb
    {{- include "mongodb.labels" . | nindent 4 }}
data:
  # Optimized MongoDB configuration for Kubernetes
  mongod.conf: |
    # Where and how to store data
    storage:
      dbPath: /data/db
      journal:
        enabled: true
      wiredTiger:
        engineConfig:
          cacheSizeGB: {{ .Values.mongodb.config.cacheSizeGB | default 0.25 }}
    
    # Network interfaces
    net:
      port: 27017
      bindIp: 0.0.0.0
      
    # Process management options
    processManagement:
      timeZoneInfo: /usr/share/zoneinfo
      
    # Security settings
    security:
      authorization: enabled
      
    # Operational settings
    operationProfiling:
      slowOpThresholdMs: 200
      mode: slowOp