apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"mongodb"},"name":"mongodb","namespace":"emcp-prod"},"spec":{"ports":[{"name":"mongodb","port":27017}],"selector":{"app":"mongodb"}}}
  labels:
    app: mongodb
  name: mongodb
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: 10.97.103.84
  clusterIPs:
    - 10.97.103.84
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: mongodb
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongodb
  sessionAffinity: None
  type: ClusterIP
