apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: emcp-prod-keycloak
    meta.helm.sh/release-namespace: emcp-prod
  creationTimestamp: "2025-02-18T07:55:12Z"
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: emcp-prod-keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/version: 26.1.0
    helm.sh/chart: keycloak-24.4.6
  name: emcp-prod-keycloak
  namespace: emcp-prod
  resourceVersion: "619093327"
  uid: c2a11433-a07b-446f-a507-f04627762a8d
spec:
  clusterIP: 10.106.81.105
  clusterIPs:
  - 10.106.81.105
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: emcp-prod-keycloak
    app.kubernetes.io/name: keycloak
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
