apiVersion: v1
kind: Service
metadata:
  annotations:
    cnpg.io/operatorVersion: 1.24.0
  creationTimestamp: "2025-03-04T15:12:46Z"
  labels:
    cnpg.io/cluster: keycloak-cnpg-cluster
  name: keycloak-cnpg-cluster-rw
  namespace: emcp-prod
  ownerReferences:
  - apiVersion: postgresql.cnpg.io/v1
    controller: true
    kind: Cluster
    name: keycloak-cnpg-cluster
    uid: bb8e3b04-4c32-4071-920e-41a8a79c1a6f
  resourceVersion: "653273828"
  uid: 071534ea-8c0e-4b83-ab92-7b8d84d92360
spec:
  clusterIP: 10.99.91.194
  clusterIPs:
  - 10.99.91.194
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    cnpg.io/cluster: keycloak-cnpg-cluster
    cnpg.io/instanceRole: primary
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
