apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"mongodb"},"name":"mongodb","namespace":"emcp-prod"},"spec":{"ports":[{"name":"mongodb","port":27017}],"selector":{"app":"mongodb"}}}
  creationTimestamp: "2024-06-06T11:09:16Z"
  labels:
    app: mongodb
  name: mongodb
  namespace: emcp-prod
  resourceVersion: "49374966"
  uid: fac29e28-71a1-485c-ba7f-c43dda868b9d
spec:
  clusterIP: 10.97.103.84
  clusterIPs:
  - 10.97.103.84
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: mongodb
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
