# charts/admin/templates/service-admin.yaml
apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: {{ .Values.namespace }}
  labels:
    app: admin
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  clusterIPs:
  - {{ .Values.service.clusterIP }}
  {{- end }}
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: web
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: admin
  sessionAffinity: None