    namespace: emcp-prod                                                           
    domain: prod.emcp.com                                                       
    replicaCount: 2 # Fewer replicas in dev                                       
                                                                                  
    image: 
      repository: harbor.enclaive.cloud/emcp/admin                                                                       
      tag: "prod-latest"                                                           
                                                                                  
    persistence:                                                                  
      size: 512Mi  # Smaller volume in dev 