apiVersion: v1
kind: Secret
metadata:
  finalizers:
    - wrangler.cattle.io/klum-secret
  name: keycloak-cnpg-cluster-ca
  namespace: {{ .Release.Namespace }}
  ownerReferences:
    - apiVersion: postgresql.cnpg.io/v1
      controller: true
      kind: Cluster
      name: keycloak-cnpg-cluster
      uid: bb8e3b04-4c32-4071-920e-41a8a79c1a6f
type: Opaque
