apiVersion: v1
kind: Service
metadata:
  annotations:
    cnpg.io/operatorVersion: 1.24.0
  labels:
    cnpg.io/cluster: keycloak-cnpg-cluster
  name: keycloak-cnpg-cluster-rw
  namespace: {{ .Release.Namespace }}
  ownerReferences:
    - apiVersion: postgresql.cnpg.io/v1
      controller: true
      kind: Cluster
      name: keycloak-cnpg-cluster
      uid: bb8e3b04-4c32-4071-920e-41a8a79c1a6f
spec:
  clusterIP: 10.99.91.194
  clusterIPs:
    - 10.99.91.194
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: keycloak-cnpg-cluster
    cnpg.io/instanceRole: primary
  sessionAffinity: None
  type: ClusterIP
