apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: emcp-prod-keycloak
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: emcp-prod-keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/version: 26.1.0
    helm.sh/chart: keycloak-24.4.6
  name: emcp-prod-keycloak-headless
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  clusterIPs:
    - None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: emcp-prod-keycloak
    app.kubernetes.io/name: keycloak
  sessionAffinity: None
  type: ClusterIP
