# This file should be saved as 'charts/redis/environments/values.dev.yaml'

namespace: emcp-dev
replicaCount: 1

image:
  repository: redis
  tag: "6.2-alpine"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 6379
  targetPort: 6379

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

redis:
  port: 6379
  config:
    maxmemory: "128mb"
    maxmemory-policy: "allkeys-lru"
    appendonly: "yes"
    appendfsync: "everysec"
  password: ""

persistence:
  enabled: true
  storageClass: "openebs-hostpath"
  size: 512Mi

probes:
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}