namespace: emcp-dev
replicaCount: 1

image:
  repository: redis
  tag: "6.2-alpine"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 6379
  targetPort: 6379

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

redis:
  port: 6379
  config:
    maxmemory: "128mb"
    maxmemoryPolicy: "allkeys-lru"  # Note: no hyphens in property name
    appendonly: "yes"
    appendfsync: "everysec"
  password: ""

persistence:
  enabled: true
  storageClass: "gp2"
  size: "512Mi"
  accessMode: "ReadWriteOnce"  # This was missing - explicit accessMode

tolerations:
- key: "CriticalAddonsOnly"
  operator: "Exists"
  effect: "NoSchedule"

probes:
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3