apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
  labels:
    app: redis
spec:
  # Remove any hardcoded ClusterIP if present
  type: {{ .Values.service.type }}
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: redis
  sessionAffinity: None
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4