// This file is auto-generated by the `update-kc-gen` command. Do not edit it manually.
// Hash: ca870c6e404cf560e3c1a26170426b74612cf9d8e4f5867052fdf6e05e303c56

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { lazy, Suspense, type ReactNode } from "react";

export type ThemeName = "enclaive";

export const themeNames: ThemeName[] = ["enclaive"];

export type KcEnvName = never;

export const kcEnvNames: KcEnvName[] = [];

export const kcEnvDefaults: Record<KcEnvName, string> = {};

/**
 * NOTE: Do not import this type except maybe in your entrypoint.
 * If you need to import the KcContext import it either from src/login/KcContext.ts or src/account/KcContext.ts.
 * Depending on the theme type you are working on.
 */
export type KcContext =
  | import("./login/KcContext.ts").KcContext
  | import("./account/KcContext.ts").KcContext;

declare global {
  interface Window {
    kcContext?: KcContext;
  }
}

export const KcLoginPage = lazy(() => import("./login/KcPage.tsx"));
export const KcAccountPage = lazy(() => import("./account/KcPage.tsx"));

export function KcPage(props: { kcContext: KcContext; fallback?: ReactNode }) {
  const { kcContext, fallback } = props;
  return (
    <Suspense fallback={fallback}>
      {(() => {
        switch (kcContext.themeType) {
          case "login":
            return <KcLoginPage kcContext={kcContext} />;
          case "account":
            return <KcAccountPage kcContext={kcContext} />;
        }
      })()}
    </Suspense>
  );
}
