apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: frontend
    {{- include "frontend.labels" . | nindent 4 }}
data:
  # Environment variables for the frontend application
  NEXT_PUBLIC_API_URL: "{{ .Values.api.url | default "https://emcp-prod.enclaive.cloud" }}"
  NEXT_PUBLIC_AUTH_URL: "{{ .Values.auth.url | default "https://auth.enclaive.cloud" }}"
  NEXT_PUBLIC_APP_URL: "{{ .Values.app.url | default "https://console.enclaive.cloud" }}"
  NEXT_PUBLIC_APP_ENV: "{{ .Values.environment | default "production" }}"
  
  # Environment variables for specific domains
  NEXT_PUBLIC_DOMAINS: "console.enclaive.cloud,govtech.enclaive.cloud,prianto.enclaive.cloud"
  
  # Feature flags
  NEXT_PUBLIC_FEATURE_FLAGS: |
    {
      "enableAnalytics": {{ .Values.features.enableAnalytics | default true }},
      "enableHelpCenter": {{ .Values.features.enableHelpCenter | default true }},
      "enableBetaFeatures": {{ .Values.features.enableBetaFeatures | default false }}
    }
  
  # Runtime configuration
  runtime-config.js: |
    window.RUNTIME_CONFIG = {
      apiUrl: "{{ .Values.api.url | default "https://emcp-prod.enclaive.cloud" }}",
      authUrl: "{{ .Values.auth.url | default "https://auth.enclaive.cloud" }}",
      environment: "{{ .Values.environment | default "production" }}",
      version: "{{ .Values.image.tag }}",
      sentryDsn: "{{ .Values.sentry.dsn | default "" }}",
      supportEmail: "{{ .Values.support.email | default "support@enclaive.cloud" }}"
    };