apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"frontend"},"name":"frontend","namespace":"emcp-prod"},"spec":{"ports":[{"name":"web","port":3000}],"selector":{"app":"frontend"}}}
  labels:
    app: frontend
  name: frontend
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: 10.97.169.158
  clusterIPs:
    - 10.97.169.158
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: web
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: frontend
  sessionAffinity: None
  type: ClusterIP
