apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"name":"frontend","namespace":"emcp-prod"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"frontend"}},"serviceName":"frontend","template":{"metadata":{"labels":{"app":"frontend"}},"spec":{"containers":[{"image":"harbor.enclaive.cloud/emcp/frontend:main-6b3895f","livenessProbe":{"failureThreshold":10,"httpGet":{"path":"/","port":3000},"initialDelaySeconds":10,"periodSeconds":3},"name":"frontend","ports":[{"containerPort":3000,"name":"web"}],"readinessProbe":{"failureThreshold":10,"httpGet":{"path":"/","port":3000},"initialDelaySeconds":10,"periodSeconds":3},"resources":{"limits":{"cpu":1,"memory":"4Gi"},"requests":{"cpu":1,"memory":"4Gi"}}}]}}}}
  creationTimestamp: "2024-11-21T06:22:45Z"
  generation: 32
  name: frontend
  namespace: emcp-prod
  resourceVersion: "780693788"
  uid: 3e1aee43-915c-479b-8f16-b789940ddaf7
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: frontend
  serviceName: frontend
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      containers:
      - image: harbor.enclaive.cloud/emcp/frontend:main-6b3895f
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        name: frontend
        ports:
        - containerPort: 3000
          name: web
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 4Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  availableReplicas: 2
  collisionCount: 0
  currentReplicas: 2
  currentRevision: frontend-69f5bcfbcf
  observedGeneration: 32
  readyReplicas: 2
  replicas: 2
  updateRevision: frontend-69f5bcfbcf
  updatedReplicas: 2
