name: Detect Chart Changes

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  pull_request:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_charts: ${{ steps.filter.outputs.changes }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Detect changed charts
        id: filter
        uses: dorny/paths-filter@v2
        with:
          list-files: json
          filters: |
            admin:
              - 'charts/admin/**'
            backend:
              - 'charts/backend/**'
            frontend:
              - 'charts/frontend/**'
            keycloak:
              - 'charts/keycloak/**'
            mongodb:
              - 'charts/mongodb/**'
            redis:
              - 'charts/redis/**'
            emcp_prod_keycloak:
              - 'charts/emcp_prod_keycloak/**'
