apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend
    {{- include "backend.labels" . | nindent 4 }}
data:
  # Configuration settings for the backend service
  settings.json: |
    {
      "app": {
        "name": "Enclaive Backend",
        "env": "{{ .Values.environment | default "production" }}",
        "logLevel": "{{ .Values.logging.level | default "info" }}"
      },
      "server": {
        "port": 8080,
        "timeout": 60000,
        "cors": {
          "enabled": true,
          "origins": ["https://admin-{{ .Values.environment }}.enclaive.cloud", "https://console.enclaive.cloud"]
        }
      },
      "database": {
        "mongodb": {
          "uri": "mongodb://{{ .Values.mongodb.username }}:{{ .Values.mongodb.password }}@{{ .Values.mongodb.host }}:{{ .Values.mongodb.port }}/{{ .Values.mongodb.database }}",
          "options": {
            "useNewUrlParser": true,
            "useUnifiedTopology": true,
            "retryWrites": true,
            "w": "majority"
          }
        },
        "redis": {
          "host": "{{ .Values.redis.host }}",
          "port": {{ .Values.redis.port }}
        }
      },
      "security": {
        "rateLimiting": {
          "enabled": true,
          "maxRequests": 100,
          "timeWindow": 60000
        }
      },
      "metrics": {
        "enabled": true,
        "path": "/metrics"
      }
    }
  
  # Application-level configuration
  app-config.json: |
    {
      "features": {
        "enableBackups": {{ .Values.features.enableBackups | default true }},
        "enableWebhooks": {{ .Values.features.enableWebhooks | default true }},
        "enableCaching": {{ .Values.features.enableCaching | default true }}
      }
    }