apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend
    {{- include "backend.labels" . | nindent 4 }}
spec:
  podManagementPolicy: OrderedReady
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: backend
  serviceName: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NODE_ENV
              value: {{ .Values.environment | default "production" }}
            - name: MONGODB_DATABASE
              value: {{ .Values.mongodb.database | default "backend_db" }}
            - name: MONGODB_HOST
              value: {{ .Values.mongodb.host | default "mongodb" }}
            - name: MONGODB_PORT
              value: {{ .Values.mongodb.port | default "27017" | quote }}
            - name: MONGODB_USER
              value: {{ .Values.mongodb.username | default "root" }}
            - name: MONGODB_PASSWORD
              value: {{ .Values.mongodb.password | default "root" }}
            - name: REDIS_HOST
              value: {{ .Values.redis.host | default "redis" }}
            - name: REDIS_PORT
              value: {{ .Values.redis.port | default "6379" | quote }}
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}