apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend
    {{- include "backend.labels" . | nindent 4 }}
spec:
  podManagementPolicy: OrderedReady
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: backend
  serviceName: backend
  template:
    metadata:
      labels:
        app: backend
        {{- include "backend.labels" . | nindent 4 }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          tty: true
          stdin: true
          env:
            {{- include "backend.envVars" . | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: web
              protocol: TCP
          volumeMounts:
            {{- range .Values.persistence.mountPaths }}
            - name: backend
              subPath: {{ .subPath }}
              mountPath: {{ .path }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: backend-jwks-keys
          configMap:
            name: backend-jwks-keys
  volumeClaimTemplates:
  - metadata:
      name: backend
    spec:
      storageClassName: {{ .Values.persistence.storageClass | quote }}
      accessModes: {{ toYaml .Values.persistence.accessModes | nindent 8 }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}