apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"name":"backend","namespace":"emcp-prod"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"backend"}},"serviceName":"backend","template":{"metadata":{"labels":{"app":"backend"}},"spec":{"containers":[{"env":[{"name":"NODE_ENV","value":"production"},{"name":"APP_ADMIN_URL","value":"https://admin-prod.enclaive.cloud"},{"name":"APP_DOMAIN_NAME","value":"app.enclaive.cloud"},{"name":"APP_FE_URL","value":"https://console.enclaive.cloud"},{"name":"APP_URL","value":"https://emcp-prod.enclaive.cloud"},{"name":"APP_WEBHOOK_PROXY_URL","value":""},{"name":"AWS_ACCESS_KEY","valueFrom":{"secretKeyRef":{"key":"AWS_ACCESS_KEY","name":"secrets"}}},{"name":"AWS_SECRET_KEY","valueFrom":{"secretKeyRef":{"key":"AWS_SECRET_KEY","name":"secrets"}}},{"name":"AZURE_AUTH_API","value":"https://login.microsoftonline.com"},{"name":"AZURE_CLIENT_ID","valueFrom":{"secretKeyRef":{"key":"AZURE_CLIENT_ID","name":"secrets"}}},{"name":"AZURE_CLIENT_SECRET","valueFrom":{"secretKeyRef":{"key":"AZURE_CLIENT_SECRET","name":"secrets"}}},{"name":"AZURE_MANAGEMENT_API","value":"https://management.azure.com/"},{"name":"AZURE_PRICE_URL","value":"https://prices.azure.com/api/retail/prices"},{"name":"AZURE_SUBSCRIPTION_ID","valueFrom":{"secretKeyRef":{"key":"AZURE_SUBSCRIPTION_ID","name":"secrets"}}},{"name":"AZURE_TENANT_ID","valueFrom":{"secretKeyRef":{"key":"AZURE_TENANT_ID","name":"secrets"}}},{"name":"BULL_DASHBOARD_ADMIN_PASSWORD","valueFrom":{"secretKeyRef":{"key":"BULL_DASHBOARD_ADMIN_PASSWORD","name":"secrets"}}},{"name":"CLOUDFLARE_ZONE_ID","value":"a153b156328f4327226bbcc85f7d1544"},{"name":"CLOUDFLARE_API_TOKEN","valueFrom":{"secretKeyRef":{"key":"CLOUDFLARE_API_TOKEN","name":"secrets"}}},{"name":"CRON_ENABLED","value":"enabled"},{"name":"DOCKER_REGISTRY_PROXY","value":"harbor.enclaive.cloud/mirror/"},{"name":"ENCRYPT_SECRET_IV","valueFrom":{"secretKeyRef":{"key":"ENCRYPT_SECRET_IV","name":"secrets"}}},{"name":"ENCRYPT_SECRET_KEY","valueFrom":{"secretKeyRef":{"key":"ENCRYPT_SECRET_KEY","name":"secrets"}}},{"name":"EXCHANGE_RATES_URL","value":"https://open.er-api.com/v6/"},{"name":"GCP_COST_TABLE","valueFrom":{"secretKeyRef":{"key":"GCP_COST_TABLE","name":"secrets"}}},{"name":"GCP_CRED","valueFrom":{"secretKeyRef":{"key":"GCP_CRED","name":"secrets"}}},{"name":"GCP_DATASET","valueFrom":{"secretKeyRef":{"key":"GCP_DATASET","name":"secrets"}}},{"name":"HUBSPOT_OWNER_ID","valueFrom":{"secretKeyRef":{"key":"HUBSPOT_OWNER_ID","name":"secrets"}}},{"name":"HUBSPOT_TOKEN","valueFrom":{"secretKeyRef":{"key":"HUBSPOT_TOKEN","name":"secrets"}}},{"name":"KC_ADMIN_EMAIL","value":"emcp.backend.service-account@enclaive.cloud"},{"name":"KC_ADMIN_PASSWORD","valueFrom":{"secretKeyRef":{"key":"KC_ADMIN_PASSWORD","name":"secrets"}}},{"name":"KC_URL","value":"https://auth.enclaive.cloud"},{"name":"KC_WEBHOOK_SECRET","valueFrom":{"secretKeyRef":{"key":"KC_WEBHOOK_SECRET","name":"secrets"}}},{"name":"KRAUD_API_URL","value":"https://api.kraudcloud.com"},{"name":"KRAUD_API_KEY","valueFrom":{"secretKeyRef":{"key":"KRAUD_API_KEY","name":"secrets"}}},{"name":"KRAUD_CRADLE_CONTEXT","value":"ucak"},{"name":"KRAUD_CRADLE_IMAGE","value":"ctr.0x.pt/kraud/cradle-snp:fd87738"},{"name":"KRAUD_CRADLE_LONGHORN_METRICS_URL","value":"http://longhorn-backend.longhorn:9500/metrics"},{"name":"KRAUD_CRADLE_PROMETHEUS_URL","value":"http://prometheus-kube-prometheus-prometheus.prometheus:9090"},{"name":"KRAUD_CRADLE_NAMESPACE","value":"emcp-prod"},{"name":"KRAUD_CRADLE_POD","value":"backend-0"},{"name":"KRAUD_HARBOR_DIST","value":"emcp-public-prod"},{"name":"MAINTENANCE_KEY","valueFrom":{"secretKeyRef":{"key":"MAINTENANCE_KEY","name":"secrets"}}},{"name":"MONGODB_DATABASE","value":"backend_db"},{"name":"MONGODB_HOST","value":"mongodb"},{"name":"MONGODB_PORT","value":"27017"},{"name":"MONGODB_USER","value":"root"},{"name":"MONGODB_PASSWORD","value":"root"},{"name":"NITRIDE_API_URL","value":"https://vhsm.enclaive.cloud"},{"name":"NITRIDE_AUDIENCE","value":"vhsm"},{"name":"NITRIDE_ISSUER","value":"emcp"},{"name":"NITRIDE_SUBJECT","value":"emcp-user"},{"name":"NITRIDE_USER_NAME","value":"emcp"},{"name":"NITRIDE_USER_PASS","valueFrom":{"secretKeyRef":{"key":"NITRIDE_USER_PASS","name":"secrets"}}},{"name":"PRICE_CURRENCY_CODE","value":"EUR"},{"name":"RE_CAPCHA_SECRET_KEY","valueFrom":{"secretKeyRef":{"key":"RE_CAPCHA_SECRET_KEY","name":"secrets"}}},{"name":"REDIS_HOST","value":"redis"},{"name":"REDIS_PORT","value":"6379"},{"name":"REDIS_FAMILY","value":"4"},{"name":"SENDGRID_API_KEY","valueFrom":{"secretKeyRef":{"key":"SENDGRID_API_KEY","name":"secrets"}}},{"name":"SENTRY_DSN","valueFrom":{"secretKeyRef":{"key":"SENTRY_DSN","name":"secrets"}}},{"name":"SMTP_PWD","valueFrom":{"secretKeyRef":{"key":"SMTP_PWD","name":"secrets"}}},{"name":"STRIPE_ACCOUNT_TAX_ID","value":"txi_1OgqnKJ6AR0K9Z7WPe78Vpj8"},{"name":"STRIPE_SECRET_KEY","valueFrom":{"secretKeyRef":{"key":"STRIPE_SECRET_KEY","name":"secrets"}}},{"name":"STRIPE_WEBHOOK_KEY","valueFrom":{"secretKeyRef":{"key":"STRIPE_WEBHOOK_KEY","name":"secrets"}}},{"name":"TERRAFORM_BACKEND_NAMESPACE","value":"default"},{"name":"TERRAFORM_BACKEND_REGION","value":"eu-central-1"},{"name":"TERRAFORM_BACKEND_BUCKET","value":"production-terraform-backend-fra"},{"name":"TERRAFORM_BACKEND_DYNAMODB","value":"production-terraform-backend-locking"},{"name":"TERRAFORM_BACKEND_ACCESS_KEY","valueFrom":{"secretKeyRef":{"key":"TERRAFORM_BACKEND_ACCESS_KEY","name":"secrets"}}},{"name":"TERRAFORM_BACKEND_SECRET_KEY","valueFrom":{"secretKeyRef":{"key":"TERRAFORM_BACKEND_SECRET_KEY","name":"secrets"}}},{"name":"TERRAFORM_BACKEND_SSE_CUSTOMER_KEY","valueFrom":{"secretKeyRef":{"key":"TERRAFORM_BACKEND_SSE_CUSTOMER_KEY","name":"secrets"}}},{"name":"TOKEN_AUDIENCE","value":"enclaive-keystore"},{"name":"TOKEN_ISSUANCE","value":"enclaive-console"},{"name":"TOKEN_SUBJECT","value":"enclaive-customer"},{"name":"VAULT_API_URL","value":"https://vhsm.enclaive.cloud"},{"name":"VAULT_API_ADMIN_USERNAME","value":"emcp"},{"name":"VAULT_API_ADMIN_PASSWORD","valueFrom":{"secretKeyRef":{"key":"VAULT_API_ADMIN_PASSWORD","name":"secrets"}}},{"name":"VAULT_API_ATTESTATION_WEBHOOK_AUTH_HASH","valueFrom":{"secretKeyRef":{"key":"VAULT_API_ATTESTATION_WEBHOOK_AUTH_HASH","name":"secrets"}}},{"name":"WEBHOOK_AUTH_HASH_SALT","valueFrom":{"secretKeyRef":{"key":"WEBHOOK_AUTH_HASH_SALT","name":"secrets"}}}],"image":"harbor.enclaive.cloud/emcp/backend0:main-60ef3de","livenessProbe":{"failureThreshold":10,"httpGet":{"path":"/ping","port":8080},"initialDelaySeconds":150,"periodSeconds":5},"name":"backend","ports":[{"containerPort":8080,"name":"web"}],"readinessProbe":{"failureThreshold":10,"httpGet":{"path":"/ping","port":8080},"initialDelaySeconds":90,"periodSeconds":5},"stdin":true,"tty":true,"volumeMounts":[{"mountPath":"/server/resources","name":"backend","subPath":"resources"},{"mountPath":"/server/public","name":"backend","subPath":"public"},{"mountPath":"/server/logs","name":"backend","subPath":"logs"}]}]}},"volumeClaimTemplates":[{"metadata":{"name":"backend"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}},"storageClassName":"longhorn"}}]}}
  name: backend
  namespace: {{ .Release.Namespace }}
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: backend
  serviceName: backend
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
            - name: APP_ADMIN_URL
              value: https://admin-prod.enclaive.cloud
            - name: APP_DOMAIN_NAME
              value: app.enclaive.cloud
            - name: APP_FE_URL
              value: https://console.enclaive.cloud
            - name: APP_URL
              value: https://emcp-prod.enclaive.cloud
            - name: APP_WEBHOOK_PROXY_URL
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: AWS_ACCESS_KEY
                  name: secrets
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: AWS_SECRET_KEY
                  name: secrets
            - name: AZURE_AUTH_API
              value: https://login.microsoftonline.com
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: AZURE_CLIENT_ID
                  name: secrets
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: AZURE_CLIENT_SECRET
                  name: secrets
            - name: AZURE_MANAGEMENT_API
              value: https://management.azure.com/
            - name: AZURE_PRICE_URL
              value: https://prices.azure.com/api/retail/prices
            - name: AZURE_SUBSCRIPTION_ID
              valueFrom:
                secretKeyRef:
                  key: AZURE_SUBSCRIPTION_ID
                  name: secrets
            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  key: AZURE_TENANT_ID
                  name: secrets
            - name: BULL_DASHBOARD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: BULL_DASHBOARD_ADMIN_PASSWORD
                  name: secrets
            - name: CLOUDFLARE_ZONE_ID
              value: a153b156328f4327226bbcc85f7d1544
            - name: CLOUDFLARE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  key: CLOUDFLARE_API_TOKEN
                  name: secrets
            - name: CRON_ENABLED
              value: enabled
            - name: DOCKER_REGISTRY_PROXY
              value: harbor.enclaive.cloud/mirror/
            - name: ENCRYPT_SECRET_IV
              valueFrom:
                secretKeyRef:
                  key: ENCRYPT_SECRET_IV
                  name: secrets
            - name: ENCRYPT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: ENCRYPT_SECRET_KEY
                  name: secrets
            - name: EXCHANGE_RATES_URL
              value: https://open.er-api.com/v6/
            - name: GCP_COST_TABLE
              valueFrom:
                secretKeyRef:
                  key: GCP_COST_TABLE
                  name: secrets
            - name: GCP_CRED
              valueFrom:
                secretKeyRef:
                  key: GCP_CRED
                  name: secrets
            - name: GCP_DATASET
              valueFrom:
                secretKeyRef:
                  key: GCP_DATASET
                  name: secrets
            - name: HUBSPOT_OWNER_ID
              valueFrom:
                secretKeyRef:
                  key: HUBSPOT_OWNER_ID
                  name: secrets
            - name: HUBSPOT_TOKEN
              valueFrom:
                secretKeyRef:
                  key: HUBSPOT_TOKEN
                  name: secrets
            - name: KC_ADMIN_EMAIL
              value: emcp.backend.service-account@enclaive.cloud
            - name: KC_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: KC_ADMIN_PASSWORD
                  name: secrets
            - name: KC_URL
              value: https://auth.enclaive.cloud
            - name: KC_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  key: KC_WEBHOOK_SECRET
                  name: secrets
            - name: KRAUD_API_URL
              value: https://api.kraudcloud.com
            - name: KRAUD_API_KEY
              valueFrom:
                secretKeyRef:
                  key: KRAUD_API_KEY
                  name: secrets
            - name: KRAUD_CRADLE_CONTEXT
              value: ucak
            - name: KRAUD_CRADLE_IMAGE
              value: ctr.0x.pt/kraud/cradle-snp:fd87738
            - name: KRAUD_CRADLE_LONGHORN_METRICS_URL
              value: http://longhorn-backend.longhorn:9500/metrics
            - name: KRAUD_CRADLE_PROMETHEUS_URL
              value: http://prometheus-kube-prometheus-prometheus.prometheus:9090
            - name: KRAUD_CRADLE_NAMESPACE
              value: emcp-prod
            - name: KRAUD_CRADLE_POD
              value: backend-0
            - name: KRAUD_HARBOR_DIST
              value: emcp-public-prod
            - name: MAINTENANCE_KEY
              valueFrom:
                secretKeyRef:
                  key: MAINTENANCE_KEY
                  name: secrets
            - name: MONGODB_DATABASE
              value: backend_db
            - name: MONGODB_HOST
              value: mongodb
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_USER
              value: root
            - name: MONGODB_PASSWORD
              value: root
            - name: NITRIDE_API_URL
              value: https://vhsm.enclaive.cloud
            - name: NITRIDE_AUDIENCE
              value: vhsm
            - name: NITRIDE_ISSUER
              value: emcp
            - name: NITRIDE_SUBJECT
              value: emcp-user
            - name: NITRIDE_USER_NAME
              value: emcp
            - name: NITRIDE_USER_PASS
              valueFrom:
                secretKeyRef:
                  key: NITRIDE_USER_PASS
                  name: secrets
            - name: PRICE_CURRENCY_CODE
              value: EUR
            - name: RE_CAPCHA_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: RE_CAPCHA_SECRET_KEY
                  name: secrets
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_FAMILY
              value: "4"
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  key: SENDGRID_API_KEY
                  name: secrets
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  key: SENTRY_DSN
                  name: secrets
            - name: SMTP_PWD
              valueFrom:
                secretKeyRef:
                  key: SMTP_PWD
                  name: secrets
            - name: STRIPE_ACCOUNT_TAX_ID
              value: txi_1OgqnKJ6AR0K9Z7WPe78Vpj8
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: STRIPE_SECRET_KEY
                  name: secrets
            - name: STRIPE_WEBHOOK_KEY
              valueFrom:
                secretKeyRef:
                  key: STRIPE_WEBHOOK_KEY
                  name: secrets
            - name: TERRAFORM_BACKEND_NAMESPACE
              value: default
            - name: TERRAFORM_BACKEND_REGION
              value: eu-central-1
            - name: TERRAFORM_BACKEND_BUCKET
              value: production-terraform-backend-fra
            - name: TERRAFORM_BACKEND_DYNAMODB
              value: production-terraform-backend-locking
            - name: TERRAFORM_BACKEND_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: TERRAFORM_BACKEND_ACCESS_KEY
                  name: secrets
            - name: TERRAFORM_BACKEND_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: TERRAFORM_BACKEND_SECRET_KEY
                  name: secrets
            - name: TERRAFORM_BACKEND_SSE_CUSTOMER_KEY
              valueFrom:
                secretKeyRef:
                  key: TERRAFORM_BACKEND_SSE_CUSTOMER_KEY
                  name: secrets
            - name: TOKEN_AUDIENCE
              value: enclaive-keystore
            - name: TOKEN_ISSUANCE
              value: enclaive-console
            - name: TOKEN_SUBJECT
              value: enclaive-customer
            - name: VAULT_API_URL
              value: https://vhsm.enclaive.cloud
            - name: VAULT_API_ADMIN_USERNAME
              value: emcp
            - name: VAULT_API_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: VAULT_API_ADMIN_PASSWORD
                  name: secrets
            - name: VAULT_API_ATTESTATION_WEBHOOK_AUTH_HASH
              valueFrom:
                secretKeyRef:
                  key: VAULT_API_ATTESTATION_WEBHOOK_AUTH_HASH
                  name: secrets
            - name: WEBHOOK_AUTH_HASH_SALT
              valueFrom:
                secretKeyRef:
                  key: WEBHOOK_AUTH_HASH_SALT
                  name: secrets
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 150
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: backend
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
            - mountPath: /server/resources
              name: backend
              subPath: resources
            - mountPath: /server/public
              name: backend
              subPath: public
            - mountPath: /server/logs
              name: backend
              subPath: logs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        name: backend
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: longhorn
        volumeMode: Filesystem
