
# charts/admin/values.yaml
# Default values for admin
# This is a YAML-formatted file.

# Environment-specific values should be defined in environments/[env].yaml
namespace: default

domain: admin.enclaive.cloud

replicaCount: 1

image:
  repository: harbor.enclaive.cloud/emcp/admin
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: harbor-creds

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

nodeSelector: {}

tolerations: []

affinity: {}

# Default logging configuration
logging:
  level: "info"
  format: "json"

# Health check probes
probes:
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 6
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 3