apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"cert-manager.io/cluster-issuer":"letsencrypt"},"name":"admin","namespace":"emcp-prod"},"spec":{"ingressClassName":"public","rules":[{"host":"admin.enclaive.cloud","http":{"paths":[{"backend":{"service":{"name":"admin","port":{"number":3000}}},"path":"/","pathType":"Prefix"}]}},{"host":"govtech.admin.enclaive.cloud","http":{"paths":[{"backend":{"service":{"name":"admin","port":{"number":3000}}},"path":"/","pathType":"Prefix"}]}},{"host":"prianto.admin.enclaive.cloud","http":{"paths":[{"backend":{"service":{"name":"admin","port":{"number":3000}}},"path":"/","pathType":"Prefix"}]}}],"tls":[{"hosts":["admin.enclaive.cloud"],"secretName":"admin-ingress-tls"},{"hosts":["govtech.admin.enclaive.cloud"],"secretName":"admin-govtech-ingress-tls"},{"hosts":["prianto.admin.enclaive.cloud"],"secretName":"admin-prianto-ingress-tls"}]}}
  creationTimestamp: "2024-06-06T15:56:20Z"
  generation: 4
  name: admin
  namespace: emcp-prod
  resourceVersion: "671781673"
  uid: 47f49009-2a1a-4db3-abc8-d88b8e0a8df1
spec:
  ingressClassName: public
  rules:
  - host: admin.enclaive.cloud
    http:
      paths:
      - backend:
          service:
            name: admin
            port:
              number: 3000
        path: /
        pathType: Prefix
  - host: govtech.admin.enclaive.cloud
    http:
      paths:
      - backend:
          service:
            name: admin
            port:
              number: 3000
        path: /
        pathType: Prefix
  - host: prianto.admin.enclaive.cloud
    http:
      paths:
      - backend:
          service:
            name: admin
            port:
              number: 3000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - admin.enclaive.cloud
    secretName: admin-ingress-tls
  - hosts:
    - govtech.admin.enclaive.cloud
    secretName: admin-govtech-ingress-tls
  - hosts:
    - prianto.admin.enclaive.cloud
    secretName: admin-prianto-ingress-tls
status:
  loadBalancer:
    ingress:
    - ip: 185.112.181.201
