apiVersion: v1
data:
  admin-password: PCpjIydAa0pUfHF3Mm5DLnN2V1lIZnAhZHZid0JAXyo=
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: emcp-prod-keycloak
    meta.helm.sh/release-namespace: emcp-prod
  creationTimestamp: "2025-02-18T07:55:12Z"
  finalizers:
  - wrangler.cattle.io/klum-secret
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: emcp-prod-keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/version: 26.1.0
    helm.sh/chart: keycloak-24.4.6
  name: emcp-prod-keycloak
  namespace: emcp-prod
  resourceVersion: "619340402"
  uid: e848bffd-bd0c-438c-aae3-66e3f52629af
type: Opaque
