apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app: mongodb
    {{- include "mongodb.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.auth.rootUsername | b64enc }}
  password: {{ .Values.auth.rootPassword | b64enc }}