apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1","kind":"CronJob","metadata":{"annotations":{},"name":"mongodb-backup-clean","namespace":"emcp-prod"},"spec":{"jobTemplate":{"spec":{"template":{"spec":{"containers":[{"command":["/bin/sh","-c","find /data/db/dump-* -mtime +7 -exec rm -rf {} \\;"],"image":"mongo:5.0.2","name":"mongodb","volumeMounts":[{"mountPath":"/data/db","name":"mongodb"}]}],"restartPolicy":"Never","volumes":[{"name":"mongodb","persistentVolumeClaim":{"claimName":"mongodb-mongodb-0"}}]}}}},"schedule":"0 3 * * 0"}}
  creationTimestamp: "2024-11-14T09:00:09Z"
  generation: 1
  name: mongodb-backup-clean
  namespace: emcp-prod
  resourceVersion: "775514955"
  uid: 68896de3-5cfb-46bc-a831-7a22620fc910
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - find /data/db/dump-* -mtime +7 -exec rm -rf {} \;
            image: mongo:5.0.2
            imagePullPolicy: IfNotPresent
            name: mongodb
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /data/db
              name: mongodb
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - name: mongodb
            persistentVolumeClaim:
              claimName: mongodb-mongodb-0
  schedule: 0 3 * * 0
  successfulJobsHistoryLimit: 3
  suspend: false
status:
  lastScheduleTime: "2025-04-27T03:00:00Z"
  lastSuccessfulTime: "2025-04-28T00:28:41Z"
