
# Default values for backend
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: 886093416603.dkr.ecr.eu-central-1.amazonaws.com/backend0
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: aws-ecr-creds

existingSecret: secrets

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Feature flags
features:
  enableBackups: false
  enableWebhooks: true
  enableCaching: true

# Logging configuration
logging:
  level: info
  format: json

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

env:
  NODE_ENV: development
  APP_ADMIN_URL: https://admin.dev.kr-ecl.de
  APP_DOMAIN_NAME: "app.enclaive.cloud"
  APP_FE_URL: https://dev.kr-ecl.de
  APP_URL: https://emcp-dev.kr-ecl.de
  APP_URL_PRIVATE: 10.107.169.79:8080
  APP_WEBHOOK_PROXY_URL: https://webhook.emcp-dev.ig.ecl.d3d1.de
  AZURE_AUTH_API: https://login.microsoftonline.com
  AZURE_MANAGEMENT_API: https://management.azure.com/
  AZURE_PRICE_URL: https://prices.azure.com/api/retail/prices
  CRON_ENABLED: enabled
  DOCKER_REGISTRY_PROXY: harbor.enclaive.cloud/mirror/
  EXCHANGE_RATES_URL: https://open.er-api.com/v6/
  KC_ADMIN_EMAIL: emcp.dev.backend.service-account@enclaive.cloud
  KC_URL: https://auth.dev.kr-ecl.de
  KRAUD_API_URL: "https://api.kraudcloud.com"
  KRAUD_CRADLE_CONTEXT: "ucak"
  KRAUD_CRADLE_IMAGE: ctr.0x.pt/kraud/cradle-snp:fd87738
  KRAUD_CRADLE_LONGHORN_METRICS_URL: http://longhorn-backend.longhorn:9500/metrics
  KRAUD_CRADLE_PROMETHEUS_URL: http://10.107.29.238:9090
  KRAUD_CRADLE_NAMESPACE: "emcp-dev"
  KRAUD_CRADLE_POD: backend-0
  KRAUD_HARBOR_DIST: emcp-public-staging
  MONGODB_DATABASE: backend_db
  MONGODB_HOST: mongodb
  MONGODB_PORT: "27017"
  MONGODB_USER: root
  MONGODB_PASSWORD: root
  NITRIDE_API_URL: https://vhsm-staging.enclaive.cloud
  NITRIDE_AUDIENCE: vhsm
  NITRIDE_ISSUER: emcp
  NITRIDE_SUBJECT: emcp-user
  NITRIDE_USER_NAME: emcp
  PRICE_CURRENCY_CODE: EUR
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_FAMILY: "4"
  TERRAFORM_BACKEND_NAMESPACE: dev
  TERRAFORM_BACKEND_REGION: eu-west-1
  TERRAFORM_BACKEND_BUCKET: staging-terraform-backend2
  TERRAFORM_BACKEND_DYNAMODB: staging-terraform-backend-locking
  CLOUDFLARE_ZONE_ID: a153b156328f4327226bbcc85f7d1544
  TOKEN_AUDIENCE: enclaive-keystore
  TOKEN_ISSUANCE: enclaive-console
  TOKEN_SUBJECT: enclaive-customer
  VAULT_API_URL: https://vhsm-staging.enclaive.cloud
  VAULT_API_ADMIN_USERNAME: emcp
  STRIPE_ACCOUNT_TAX_ID: txi_1OgqnKJ6AR0K9Z7WPe78Vpj8
secretEnv:
  AWS_ACCESS_KEY: ""
  AWS_SECRET_KEY: ""
  AZURE_CLIENT_ID: ""
  AZURE_CLIENT_SECRET: ""
  AZURE_SUBSCRIPTION_ID: ""
  AZURE_TENANT_ID: ""
  BULL_DASHBOARD_ADMIN_PASSWORD: ""
  CLOUDFLARE_API_TOKEN: ""
  ENCRYPT_SECRET_IV: ""
  ENCRYPT_SECRET_KEY: ""
  GCP_COST_TABLE: ""
  GCP_CRED: ""
  GCP_DATASET: ""
  HUBSPOT_OWNER_ID: ""
  HUBSPOT_TOKEN: ""
  KC_ADMIN_PASSWORD: ""
  KC_WEBHOOK_SECRET: ""
  KRAUD_API_KEY: ""
  MAINTENANCE_KEY: ""
  NITRIDE_USER_PASS: ""
  RE_CAPCHA_SECRET_KEY: ""
  SENDGRID_API_KEY: ""
  SENTRY_DSN: ""
  SMTP_PWD: ""
  STRIPE_SECRET_KEY: ""
  STRIPE_WEBHOOK_KEY: ""
  TERRAFORM_BACKEND_ACCESS_KEY: ""
  TERRAFORM_BACKEND_SECRET_KEY: ""
  TERRAFORM_BACKEND_SSE_CUSTOMER_KEY: ""
  VAULT_API_ADMIN_PASSWORD: ""
  VAULT_API_ATTESTATION_WEBHOOK_AUTH_HASH: ""
  WEBHOOK_AUTH_HASH_SALT: ""

ingress:
  enabled: true
  className: intranet
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: emcp-dev.kr-ecl.de
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: backend-ingress-tls
      hosts:
        - emcp-dev.kr-ecl.de

# Webhook ingress configuration
webhookIngress:
  enabled: true
  className: public
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: webhook.emcp-dev.ig.ecl.d3d1.de
      paths:
        - path: /webhook
          pathType: Prefix
  tls:
    - secretName: backend-webhook-ingress-tls
      hosts:
        - webhook.emcp-dev.ig.ecl.d3d1.de

persistence:
  enabled: true
  storageClass: gp3
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  mountPaths:
    - name: backend
      subPath: resources
      path: /server/resources
    - name: backend
      subPath: public
      path: /server/public
  volumes:
    name: backend-jwks-keys