
# Default values for backend
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: 886093416603.dkr.ecr.eu-central-1.amazonaws.com/backend0
  tag: dev
  pullPolicy: Always

imagePullSecrets:
  - name: aws-ecr-creds

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Database configurations
mongodb:
  host: mongodb
  port: 27017
  database: backend_db
  username: root
  password: root

# Redis configurations
redis:
  host: redis
  port: 6379

# Feature flags
features:
  enableBackups: false
  enableWebhooks: true
  enableCaching: true

# Logging configuration
logging:
  level: info
  format: json