# Default values for mongodb
namespace: default

replicaCount: 1

image:
  repository: mongo
  tag: "5.0.2"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: harbor-creds

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 27017
  targetPort: 27017

# MongoDB credentials
auth:
  rootUsername: root
  rootPassword: root
  # For production, use secretRef
  # secretRef:
  #   name: mongodb-credentials
  #   userKey: username
  #   passwordKey: password

# Minimal resources to save costs
resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: true
  storageClass: "longhorn"
  size: 1Gi

# Backup configuration - minimal approach
backup:
  enabled: true
  # Schedule in cron format
  schedule: "0 2 * * 0"  # Only once per week on Sunday at 2am
  # Number of days to keep backups
  retentionDays: 7
  # Database to backup
  database: backend_db
  # Cleanup cron schedule
  cleanupSchedule: "0 3 * * 0"  # Every Sunday at 3am