apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
    volume.kubernetes.io/storage-provisioner: driver.longhorn.io
  creationTimestamp: "2024-11-14T09:38:37Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: backend
    recurring-job-group.longhorn.io/default: enabled
  name: backend-backend-0
  namespace: emcp-prod
  resourceVersion: "556403340"
  uid: 58ed77df-c4c0-46ba-bc0b-6dabb2d18c2d
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-58ed77df-c4c0-46ba-bc0b-6dabb2d18c2d
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  phase: Bound
