apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
    volume.kubernetes.io/storage-provisioner: driver.longhorn.io
  creationTimestamp: "2024-06-06T11:09:16Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: mongodb
    recurring-job-group.longhorn.io/default: enabled
  name: mongodb-mongodb-0
  namespace: emcp-prod
  resourceVersion: "556404118"
  uid: 33e77280-9649-4b45-84e9-28e10efeefe8
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-33e77280-9649-4b45-84e9-28e10efeefe8
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  phase: Bound
