# Default values for redis
namespace: default

replicaCount: 1

image:
  repository: redis
  tag: "6.2-alpine"  # Using Alpine for smaller image size
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: harbor-creds

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 6379
  targetPort: 6379
  # Optional: Set ipFamilyPolicy configuration if needed
  ipFamilyPolicy: SingleStack  # Changed to SingleStack to reduce complexity

# Minimal resources to save costs
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: true
  storageClass: "longhorn"
  size: 512Mi  # Minimal storage to reduce costs

# Redis configuration options
redis:
  config:
    maxmemory: 200mb
    maxmemoryPolicy: allkeys-lru

# Environment-specific configurations should be in environments/[env].yaml